version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_USER: ${DB_USER:-canoline}
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_PASSWORD: ${DB_PASSWORD:-canoline}
      MYSQL_DATABASE: ${DB_DATABASE:-canoline_dev}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./docker/mysql/tmp:/var/lib/mysql
      - ./docker/mysql/etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
  php:
    extends:
      file: ./app-common.yml
      service: app
    depends_on:
      - mysql
      - redis
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/canoline.conf:/etc/nginx/conf.d/canoline.conf
      - ./public:/usr/src/canoline/public
    ports:
      - "80:80"
    depends_on:
      - php
  redis:
    image: library/redis:6.0.10-alpine
  queue:
    extends:
      file: ./app-common.yml
      service: app
    depends_on:
      - mysql
      - redis
    entrypoint:
      - "/usr/bin/supervisord"
      - "-n"
      - "-c"
      - "/etc/supervisord.conf"